package ide;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 15 23:13:20 GMT-04:00 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCION_DIBUJAR = 12;
  public static final int POSICION = 18;
  public static final int LLAVE_ABRE = 5;
  public static final int TIPO_PIEZA = 10;
  public static final int LLAVE_CIERRA = 6;
  public static final int FUNCION_REPRODUCIR = 13;
  public static final int FIN_LINEA = 4;
  public static final int SECCION_VARIABLES = 16;
  public static final int SUMA = 8;
  public static final int VARIABLE = 19;
  public static final int SECCION_NOMBREPROGRAMA = 15;
  public static final int NOTA = 17;
  public static final int COMMA = 7;
  public static final int ASIGNACION = 3;
  public static final int EOF = 0;
  public static final int TIEMPO = 11;
  public static final int error = 1;
  public static final int ESPACIOS = 2;
  public static final int FIN = 14;
  public static final int EXITO = 9;
  public static final int INICIO = 20;
}

